### PR TITLE
Fix version and other ThisBuild settings so cross-project pub works.

### PR DESCRIPTION
**Pull request by aappddeevv**
Related to: create a scalajs version #21

### CODE REVIEW

**Comment by Jacoby6000** [comment]
Until the maintainer publishes the updated library, I've published `0.3.0` for `2.10`, 2.11`, and `2.12` as well as scalajs.  Additionally, I republished `0.2.0` crossbuilt for `2.12` if anybody wants to use that.

For scala: `"com.github.jacoby6000" %% "retry" % "<version>"` 
For scalajs: `"com.github.jacoby6000" %%% "retry" % "<version>"`

**Comment by Jacoby6000** [comment]
@softprops if somebody could look in to this it'd be great!

**Comment by adamw** [comment]
I think that's resolved now with 0.3.0

**Comment by Jacoby6000** [comment]
I'm going to delete my fork. Anybody who gets here should use the official version.

**Comment by emilypi** [comment]
Thanks @Jacoby6000 for taking it upon yourself to provide an up to date release.

**Pull request closed without merging**
